import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { CartProvider, SearchProvider } from "@/components/CartProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import CookieConsent from "@/components/CookieConsent ";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  // await storeUserInSupabase()

  return (

    <ClerkProvider dynamic>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SearchProvider>
            <CartProvider>
              <div className="flex flex-col min-h-screen">
                <Header />
                <main className="flex-1">

                  {children}
                  <CookieConsent />

                  {/* Sonner Toaster component for the entire app */}
                  <Toaster richColors position="top-center" />
                </main>
              </div>
            </CartProvider>
          </SearchProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
